version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app

  db: 
    image: postgres:14
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: