services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=DB
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:8000
volumes:
  postgres_data:
