services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_NAME=DB
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:8000
